/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'stm32f429_zdyz_board' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* ARM::CMSIS-Compiler:STDERR:Event Recorder@1.1.0 */
#define RTE_CMSIS_Compiler_STDERR                /* CMSIS-Compiler STDERR */
#define RTE_CMSIS_Compiler_STDERR_Event_Recorder /* CMSIS-Compiler STDERR: Event Recorder */
/* ARM::CMSIS-Compiler:STDOUT:Event Recorder@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Event_Recorder /* CMSIS-Compiler STDOUT: Event Recorder */
/* ARM::CMSIS-View:Event Recorder&DAP@1.6.0 */
#define RTE_CMSIS_View_EventRecorder
#define RTE_CMSIS_View_EventRecorder_DAP
/* ARM::CMSIS:RTOS2:FreeRTOS&Cortex-M@11.2.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_FreeRTOS        /* CMSIS-RTOS2 FreeRTOS */
/* ARM::RTOS&FreeRTOS:Config&CMSIS RTOS2@11.2.0 */
#define RTE_RTOS_FreeRTOS_CONFIG_RTOS2  /* RTOS FreeRTOS Config for CMSIS RTOS2 API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@11.2.0 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Event Groups@11.2.0 */
#define RTE_RTOS_FreeRTOS_EVENTGROUPS   /* RTOS FreeRTOS Event Groups */
/* ARM::RTOS&FreeRTOS:Heap&Heap_4@11.2.0 */
#define RTE_RTOS_FreeRTOS_HEAP_4        /* RTOS FreeRTOS Heap 4 */
/* ARM::RTOS&FreeRTOS:Timers@11.2.0 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */


#endif /* RTE_COMPONENTS_H */
